# Change 'comments' to true for Disqus comments
#disqus:
#  comments: false
#  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
#google-ID: 'UA-112060364-1'

menu:
# - {name: 'Projects',   url: 'projects.html'}
# - {name: 'Papers', url: 'papers.html'}
# - {name: 'Teaching', url: 'teaching.html'}
- {name: 'Presentations', url: 'presentations.html'}
- {name: 'Contact', url: 'contact.html'}
# - {name: 'CV', url: 'cv.html'}
- {name: 'Experiences', url: 'experiences.html'}
- {name: 'Education', url: 'education.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'orcid',     link: 'https://orcid.org/0000-0003-4592-8120'}
# - {icon: 'github',     link: 'https://www.github.com/lenpaul'}
# - {icon: 'twitter',    link: 'https://twitter.com/paululele'}
- {icon: 'researchgate',   link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'linkedin',   link: 'https://www.researchgate.net/profile/Letong-Jin'}
# - {icon: 'envelope',   link: 'mailto:jacksonking.jlt@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
# pagination:
#  next_page: 'Newer'
#  previous_page: 'Older'

# sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy:'

# post_date_prefix: 'Written on'
